workspace:
  launch:
    autoOpenWebIDE: true
copyRepo:

knowledgeBase:
  roles:
    - name: 60s
      prompt: |
        当用户输入时间时
        例如：当前时间是2025-10-27，那么就是 2025-10-27.md
        需要是md里面的内容。
        然后分析

  defaultRole: 60s
