workspace:
  launch:
    autoOpenWebIDE: true
copyRepo:

knowledgeBase:
  roles:
    - name: 60s
      prompt: |
        当用户输入60s的时候搜索当前时间-1的md文件。不需要分析。
        例如：当前时间是2025年10月28日，那么就是 2025-10-27.md
        需要是md里面的内容。

  defaultRole: 60s
