$:
  vscode:
    - docker:
        image: docker.cnb.cool/ohao/learn/python:3.12.11
      services:
        - vscode
        - docker

main:
  "crontab: 53 05 * * *":
    - name: 定时任务
      stages: 
        - name: 60s
          image: docker.cnb.cool/ohao/learn/python:3.12.11
          script: |
            python 60s.py latest
            git add .
            git commit -m "自动提交：$(date "+%Y-%m-%d %H:%M:%S")"
            git push
  push:
    - services:
        - docker
      imports:
        - https://cnb.cool/IIIStudio/key/-/blob/main/github/env.yml
      stages:
        - name: 同步到GitHub
          image: tencentcom/git-sync 
          settings:
            target_url: https://github.com/IIIStudio/CNB60s.git
            auth_type: https
            username: ${GIT_USERNAME} 
            password: ${GIT_ACCESS_TOKEN}
            branch: main
            git_user: ${GIT_USERNAME}
            git_email: ${GIT_EMAIL}