$:
  vscode:
    - docker:
        # 指定云原生开发启动时的基础镜像为当前镜像
        image: docker.cnb.cool/ohao/learn/python:3.12.11
      services:
        - vscode
        - docker
      stages:
        - name: set code-server
          script: ln -sf  /workspace/settings.json /root/.local/share/code-server/User/settings.json